import { useState } from 'react';
import {
  AlertTriangle, ArrowUpRight, BarChart3, Camera, CheckCircle2, ChevronDown,
  CloudRain, Droplets, Image, Info, LocateFixed, Menu, Navigation, Plus, Send,
  ShieldCheck, Thermometer, Upload, Users, Waves, X,
} from 'lucide-react';
import { RiskMap } from './components/map/RiskMap';
import { WeatherAtmosphere } from './components/layout/WeatherAtmosphere';
import { PravahLogo } from './components/layout/PravahLogo';
import {
  aiImageAnalysis, citizenReports, environmentalConditions, locationRisks,
  recommendation, riskFactors, riskPrediction, riskSummary, weatherState, weatherTheme,
} from './data/mockData';
import type { RiskLevel } from './types/domain';

const levelStyle: Record<RiskLevel, string> = {
  LOW: 'text-[#58c98b] bg-[#58c98b]/10 border-[#58c98b]/25',
  MODERATE: 'text-[#eec04a] bg-[#eec04a]/10 border-[#eec04a]/25',
  HIGH: 'text-[#ef603e] bg-[#ef603e]/10 border-[#ef603e]/25',
  CRITICAL: 'text-[#f0445f] bg-[#f0445f]/10 border-[#f0445f]/25',
};

function Badge({ level }: { level: RiskLevel }) {
  return <span className={`risk-badge inline-flex items-center gap-1.5 rounded-md border px-2 py-1 text-[10px] font-bold tracking-[.14em] ${levelStyle[level]}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{level}</span>;
}

function Panel({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <section className={`rounded-xl border border-[#21403A] bg-[#112321]/95 ${className}`}>{children}</section>;
}

function SectionTitle({ eyebrow, title, icon: Icon }: { eyebrow: string; title: string; icon: typeof BarChart3 }) {
  return <div className="mb-5 flex items-center gap-3"><div className="rounded-lg border border-[#21403A] bg-[#142A26] p-2 text-[#48C7D4]"><Icon size={16} /></div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#68827B]">{eyebrow}</p><h2 className="font-display text-base font-semibold text-[#F1F7F4]">{title}</h2></div></div>;
}

function App() {
  const [reportOpen, setReportOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <div className="app-shell relative min-h-screen bg-[#f4f7f6] text-[#172321]">
      <WeatherAtmosphere state={weatherState} />
      <header className="relative z-10 border-b border-[#1b322b] bg-[#081410]/90">
        <div className="mx-auto flex max-w-[1600px] items-center justify-between gap-4 px-4 py-4 sm:px-8">
          <div className="flex items-center gap-3"><PravahLogo size={40} /><div><p className="font-display text-lg font-bold tracking-tight text-white">PRAVAH</p><p className="hidden text-[10px] tracking-wide text-[#75958a] sm:block">See the flow. Predict the risk.</p></div></div>
          <div className="hidden items-center gap-3 md:flex"><button className="flex items-center gap-2 rounded-lg border border-[#29453d] bg-[#10231d] px-3 py-2 text-xs text-[#bfd5cc]"><LocateFixed size={14} className="text-[#48c7d4]" /> Cuttack, Odisha <ChevronDown size={13} /></button><div className="flex items-center gap-2 text-[10px] tracking-wide text-[#91aaa3]"><span className="live-dot h-1.5 w-1.5 rounded-full bg-[#48c7d4]" /><span><strong className="font-bold tracking-[.14em] text-[#7de2b0]">LIVE CONDITIONS</strong><br />{weatherTheme.label} · {environmentalConditions.rainfall} mm · {environmentalConditions.rainfallTrend}</span></div><button className="rounded-lg border border-[#29453d] px-3 py-2 text-xs text-[#89a49a]">Storm mode</button><button onClick={() => setReportOpen(true)} className="flex items-center gap-2 rounded-lg bg-[#7de2b0] px-3 py-2 text-xs font-bold text-[#092017] transition hover:bg-[#b0f3c9]"><Plus size={14} /> Report flooding</button></div>
          <button className="rounded-lg border border-[#29453d] p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X size={18} /> : <Menu size={18} />}</button>
        </div>
        {menuOpen && <div className="flex flex-col gap-3 border-t border-[#1b322b] px-4 py-4 md:hidden"><button className="flex items-center gap-2 rounded-lg border border-[#29453d] bg-[#10231d] px-3 py-2 text-left text-xs"><LocateFixed size={14} /> Cuttack, Odisha</button><button onClick={() => setReportOpen(true)} className="rounded-lg bg-[#8ee5b2] px-3 py-2 text-xs font-bold text-[#092017]">Report flooding</button></div>}
      </header>

      <main className="relative z-10 mx-auto max-w-[1600px] space-y-5 px-4 py-5 sm:px-8 lg:py-7">
        <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mb-1 text-[10px] font-bold uppercase tracking-[.2em] text-[#71ad96]">Environmental intelligence / Live workspace</p><h1 className="font-display text-2xl font-semibold tracking-tight text-white sm:text-3xl">Cuttack risk overview</h1><p className="mt-2 flex items-center gap-2 text-xs text-[#91aaa3]"><CloudRain size={14} className="text-[#48c7d4]" /><strong className="font-medium text-[#c1d7d0]">{weatherTheme.label}</strong><span>· {environmentalConditions.rainfall} mm accumulated · {environmentalConditions.rainfallTrend}</span></p></div><p className="text-xs text-[#66837a]">Last synchronized {riskSummary.observedAt.replace('Updated ', '')}</p></div>
        <div className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(330px,.7fr)]">
          <div className="relative"><RiskMap locations={locationRisks} /><Panel className="absolute bottom-5 right-5 hidden w-[292px] p-4 shadow-2xl shadow-black/40 sm:block"><div className="mb-3 flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#91aaa3]">Current location risk</p><p className="mt-1 text-sm text-[#d0e0da]">{riskSummary.location}</p></div><Badge level={riskSummary.category} /></div><div className="flex items-end gap-2"><strong className="font-display text-6xl leading-none text-white">{riskSummary.score}</strong><span className="mb-1 text-xs text-[#91aaa1]">/ 100</span><span className="mb-1 ml-auto text-xs font-semibold text-[#ff7a45]">↗ {riskSummary.trend}</span></div><p className="mt-3 text-xs leading-relaxed text-[#a2b8b0]">{riskSummary.explanation}</p><div className="mt-3 flex items-center justify-between border-t border-[#244039] pt-3 text-[10px] text-[#91aaa3]"><span>Next risk outlook</span><strong className="text-[#ff4d6d]">{riskSummary.prediction}</strong></div></Panel></div>
          <div className="space-y-5"><Panel className="p-5 sm:hidden"><div className="mb-3 flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#75958a]">Current location risk</p><p className="mt-1 text-sm text-[#bad0c7]">{riskSummary.location}</p></div><Badge level={riskSummary.category} /></div><div className="flex items-end gap-2"><strong className="font-display text-5xl text-white">{riskSummary.score}</strong><span className="text-xs text-[#6d8a80]">/ 100</span><span className="ml-auto text-xs font-semibold text-[#ef603e]">↗ {riskSummary.trend}</span></div><p className="mt-3 text-xs leading-relaxed text-[#91aaa1]">{riskSummary.explanation}</p></Panel><Panel className="border-[#8ee5b2]/20 bg-[#10261e] p-5"><div className="flex gap-3"><div className="mt-0.5 rounded-lg bg-[#8ee5b2]/10 p-2 text-[#8ee5b2]"><Navigation size={17} /></div><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#71ad96]">Recommended action</p><h2 className="mt-1 font-display text-lg font-semibold text-white">{recommendation.title}</h2><p className="mt-2 text-sm leading-relaxed text-[#b3cac0]">{recommendation.message}</p><p className="mt-3 text-[10px] text-[#719187]">{recommendation.basis}</p></div></div></Panel><Panel className="p-5"><SectionTitle eyebrow="Near-term outlook" title="Prediction estimate" icon={BarChart3} /><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-[#66867b]">Current</p><p className="mt-1 font-display text-xl font-bold text-[#ef603e]">{riskPrediction.current}</p></div><ArrowUpRight className="text-[#ef603e]" /><div><p className="text-[10px] uppercase tracking-wider text-[#66867b]">Potential</p><p className="mt-1 font-display text-xl font-bold text-[#f0445f]">{riskPrediction.potential}</p></div><div className="border-l border-[#29453d] pl-4"><p className="text-[10px] uppercase tracking-wider text-[#66867b]">Confidence</p><p className="mt-1 text-sm font-semibold text-[#eec04a]">{riskPrediction.confidence}</p></div></div><p className="mt-4 text-xs leading-relaxed text-[#91aaa1]">{riskPrediction.explanation} <span className="text-[#66867b]">Not a guaranteed forecast.</span></p></Panel></div>
        </div>

        <Panel className="p-5"><SectionTitle eyebrow="Observed conditions" title="Environmental conditions" icon={Waves} /><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{[{label:'Rainfall',value:`${environmentalConditions.rainfall} ${environmentalConditions.rainfallUnit}`,sub:'Accumulated',icon:CloudRain,color:'text-[#65b9e3]'},{label:'Rainfall trend',value:environmentalConditions.rainfallTrend,sub:'Last observation',icon:BarChart3,color:'text-[#ef603e]'},{label:'Temperature',value:`${environmentalConditions.temperature}°C`,sub:'Current',icon:Thermometer,color:'text-[#eec04a]'},{label:'Humidity',value:`${environmentalConditions.humidity}%`,sub:'Relative',icon:Droplets,color:'text-[#65b9e3]'},{label:'Water depth',value:`${environmentalConditions.waterDepth} cm`,sub:'Reported average',icon:Waves,color:'text-[#65b9e3]'},{label:'Citizen reports',value:environmentalConditions.citizenReports.toString(),sub:'Recent reports',icon:Users,color:'text-[#8ee5b2]'}].map(({label,value,sub,icon:Icon,color})=><div key={label} className="rounded-xl border border-[#203a32] bg-[#10221d] p-3"><Icon size={16} className={`mb-4 ${color}`} /><p className="text-[10px] text-[#719187]">{label}</p><p className="mt-1 font-display text-lg font-semibold text-[#e0ece7]">{value}</p><p className="mt-1 text-[10px] text-[#58766c]">{sub}</p></div>)}</div></Panel>

        <div className="grid gap-5 lg:grid-cols-2"><Panel className="p-5"><SectionTitle eyebrow="Explainable assessment" title="What is driving risk?" icon={AlertTriangle} /><div className="mb-4 rounded-lg border border-[#29453d] bg-[#10221d] p-3 text-xs text-[#9bb4aa]"><Info size={14} className="mr-2 inline text-[#eec04a]" /> Initial hackathon engineering assumptions — not scientifically validated thresholds.</div>{riskFactors.map((factor)=><div key={factor.name} className="mb-4 last:mb-0"><div className="mb-1.5 flex justify-between text-xs"><span className="text-[#c0d4cb]">{factor.name}</span><strong className="text-[#8ee5b2]">{factor.weight}%</strong></div><div className="h-1.5 rounded-full bg-[#19342b]"><div className="h-full rounded-full bg-[#73c9a0]" style={{width:`${factor.weight * 4}%`}} /></div><p className="mt-1 text-[10px] text-[#5f7e73]">{factor.description}</p></div>)}</Panel><Panel className="p-5"><SectionTitle eyebrow="Risk context" title="Why this location is high risk" icon={ShieldCheck} /><ul className="space-y-4 text-sm text-[#afc6bc]">{['Rainfall has increased over the recent observation period.','Multiple citizen reports indicate rising water levels.','Reported water depth is increasing.','Historical/geographical vulnerability contributes to the score.'].map(item=><li key={item} className="flex gap-3"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#73c9a0]" />{item}</li>)}</ul><p className="mt-5 border-t border-[#203a32] pt-4 text-[10px] leading-relaxed text-[#66867b]">The explanation is demonstration data and will eventually be supplied by the risk API.</p></Panel></div>

        <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Panel className="p-5"><SectionTitle eyebrow="Community observations" title="Citizen reports" icon={Users} /><div className="space-y-2">{citizenReports.map(report=><div key={report.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#203a32] bg-[#10221d] p-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#18382d] text-[#8ee5b2]"><Waves size={15} /></div><div className="min-w-[100px] flex-1"><p className="text-sm font-semibold text-[#d4e3dd]">{report.location}</p><p className="text-[10px] text-[#658279]">{report.timestamp} · Water depth: {report.waterDepth} cm</p></div><Badge level={report.severity} /><span className="text-[10px] text-[#78958a]">{report.status}</span>{report.hasImage && <Image size={15} className="text-[#73c9a0]" aria-label="Image attached" />}</div>)}</div></Panel><Panel className="p-5"><SectionTitle eyebrow="Supporting evidence" title="AI image analysis" icon={Camera} /><div className="flex gap-3"><div className="flex h-24 w-28 shrink-0 items-center justify-center rounded-xl border border-dashed border-[#41665a] bg-[#102a21] text-[#668f7e]"><Camera size={23} /></div><div><p className="text-xs font-semibold text-[#c4d8ce]">{aiImageAnalysis.submittedImageLabel}</p>{aiImageAnalysis.observations.map(observation=><p key={observation} className="mt-1 text-[10px] text-[#87a59a]">• {observation}</p>)}</div></div><div className="mt-4 flex items-center justify-between border-t border-[#203a32] pt-3"><div><p className="text-[10px] uppercase tracking-wider text-[#66867b]">Estimated severity</p><Badge level={aiImageAnalysis.estimatedSeverity} /></div><div className="text-right"><p className="text-[10px] uppercase tracking-wider text-[#66867b]">Confidence</p><p className="font-display text-lg font-bold text-white">{aiImageAnalysis.confidence.toFixed(2)}</p></div></div><p className="mt-3 text-[10px] text-[#eec04a]">AI-assisted observation · supporting evidence, not ground truth.</p></Panel></div>
      </main>

      {reportOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-labelledby="report-title"><div className="w-full max-w-md rounded-2xl border border-[#315448] bg-[#0d1b18] p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#71ad96]">Future workflow preview</p><h2 id="report-title" className="font-display text-xl font-semibold text-white">Report flooding</h2></div><button onClick={() => setReportOpen(false)} aria-label="Close report form"><X size={18} /></button></div><div className="space-y-3"><label className="block text-xs text-[#91aaa1]">Location<input className="mt-1 w-full rounded-lg border border-[#29453d] bg-[#10221d] px-3 py-2 text-sm outline-none focus:border-[#8ee5b2]" placeholder="e.g. Badambadi" /></label><label className="block text-xs text-[#91aaa1]">Water depth<input className="mt-1 w-full rounded-lg border border-[#29453d] bg-[#10221d] px-3 py-2 text-sm outline-none focus:border-[#8ee5b2]" placeholder="Centimetres" /></label><label className="block text-xs text-[#91aaa1]">Description<textarea className="mt-1 h-20 w-full resize-none rounded-lg border border-[#29453d] bg-[#10221d] px-3 py-2 text-sm outline-none focus:border-[#8ee5b2]" placeholder="What are you observing?" /></label><button className="flex w-full items-center justify-center gap-2 rounded-lg border border-dashed border-[#41665a] py-3 text-xs text-[#91aaa1]"><Upload size={15} /> Attach image (not uploaded in demo)</button></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setReportOpen(false)} className="rounded-lg px-3 py-2 text-xs text-[#88a39a]">Cancel</button><button onClick={() => setReportOpen(false)} className="flex items-center gap-2 rounded-lg bg-[#8ee5b2] px-4 py-2 text-xs font-bold text-[#092017]"><Send size={13} /> Save demo report</button></div></div></div>}
    </div>
  );
}

export default App;
